### ISSUE TITLE
What's up with New South Wales?

### ISSUE THREAD

**Issue by rugk** [ENT8R/blacklistr#18] opened 2018-05-14 21:15 UTC
![new south wales](https://user-images.githubusercontent.com/11966684/40023792-7d672b32-57cc-11e8-9a5b-8fe926b9cd5c.gif)

So does it belong to Australia or not? And if it does (as the areas overlap each other*) why should one select/use New South Wales?

\* Actually it seems New South Wales is completely inside Australia here…

**Comment by ENT8R** [comment] 2018-05-15 12:20
It is just there for the sake of completeness... The different states of the USA can also be selected (not by clicking on them but by writing their country codes). The behavior is indeed kind of inconsistent as you can't select the other Australian states like `AU-QLD` or `AU-SA`. So I think I have to handle this the same way like it is already done for `EU` and `FX` (bringing them to the back, so they can't be selected by clicking on them):
https://github.com/ENT8R/blacklistr/blob/ce6b32de3e2f51e6a59641c58777cb9a4ff1fd80/js/main.js#L9

**Comment by ENT8R** [comment] 2018-05-15 12:21
But it is kind of strange that only this one state is affected by this... Maybe the source file by JOSM is kind of corrupt... I will have a look at it.

**Comment by rugk** [comment] 2018-05-15 12:34
> The different states of the USA can also be selected

Hu, but can you actually select the whole US? Okay maybe, but you cannot do so but clicking on it… (as you, well…, can't click on it without selecting a state):laughing:

**Comment by ENT8R** [comment] 2018-05-15 12:42
The problem is that `AU-NSW` is a relation in OSM instead of a simple way. Those relations can be found later in the source file which results in the fact that the relations are also loaded later on the map (so they basically have a higher priority):
`AU-NSW` can be found at line 4875:
https://github.com/ENT8R/blacklistr/blob/master/assets/boundaries.geojson?short_path=bb2c751#L4875-L4885
but `AU` is already at https://github.com/ENT8R/blacklistr/blob/master/assets/boundaries.geojson?short_path=bb2c751#L4818-L4834
and the other states of Australia are even earlier at https://github.com/ENT8R/blacklistr/blob/master/assets/boundaries.geojson?short_path=bb2c751#L2778-L2843
So I think the only way to fix this is to add this to the array of country codes which should be brought to the back...

> can't click on it without selecting a state

Did you tested it? I can click on the whole US and it never selects a state...

**Comment by rugk** [comment] 2018-05-15 13:14
> Did you tested it? I can click on the whole US and it never selects a state...

No, that was what I remembered. Maybe the behaviour changed, indeed I can now only select the whole US… don't know if that is really better though.

**Comment by ENT8R** [comment] 2018-05-15 15:27
This should be fixed now...

**Closed as completed** 2018-05-15 15:27 UTC
Labels: bug

**Comment by rugk** [comment] 2018-05-15 17:05
It is, thanks. :smile:
